import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { useEffect, useState } from 'react'
import axios from 'axios'
import Image from 'next/image'
import { addtocart } from '@/store/cartSlice'
import { useDispatch } from 'react-redux'
const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [data,setdata]=useState([]);
  useEffect(()=>{
const getdata=async()=>{
  const  {data}=await axios.get("https://fakestoreapi.com/products");
  setdata(data);
  console.log(data)
}
getdata();
  },[])
  const dispatch=useDispatch();
  const handleadd=(item)=>{
    dispatch(addtocart(item))
  }
  return (
    <>
      <Head>
        <title>Home page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="https://avatars.githubusercontent.com/u/102220613?v=4" />

      </Head>
    
      <main className={styles.main}>
 <div className={styles.container}>
  {
    data.map((ele)=>{
      return (
        <div className={styles.card}>
        <h3>{ele.title}</h3>
        <img src={ele.image} alt={ele.image} width={100} />
        <p>{ele.price}</p>
        <p>{ele.description}</p>
        <button onClick={()=>handleadd(ele)}>Add</button>
      </div>
      )
    })
  }

 
 </div>
      
      </main>
    </>
  )
}
