import Head from 'next/head'
import React from 'react'

const Services = () => {
  return (
    <div>
         <Head>
        <title>Services page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="https://avatars.githubusercontent.com/u/102220613?v=4" />

      </Head>
      service page
    </div>
  )
}

export default Services
